spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/admin
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    open-in-view: false

server:
  port: 8080
